import streamlit as st
from io import BytesIO
from datetime import date, datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from database.database import (
    add_invoice,
    get_invoice_details,
    get_clients,
    invoice_exists,
    update_invoice_status,
    update_invoice_dates,
    update_overdue_invoices,
    add_payment_event,
    get_payment_events,
    get_total_paid_for_invoice,
)


# --------------------------------------------------
# HELPERS
# --------------------------------------------------

def parse_date(value):
    if not value:
        return None

    try:
        return datetime.strptime(
            value,
            "%Y-%m-%d"
        ).date()

    except (ValueError, TypeError):
        return None


def get_due_message(due_date_value, status):
    due = parse_date(due_date_value)

    if not due:
        return "No due date"

    if status == "Paid":
        return "Paid"

    days = (due - date.today()).days

    if days < 0:
        return f"{abs(days)} day(s) overdue"

    if days == 0:
        return "Due today"

    if days == 1:
        return "Due tomorrow"

    return f"Due in {days} days"


# --------------------------------------------------
# PDF GENERATOR
# --------------------------------------------------

def generate_invoice_pdf(
    invoice_number,
    client,
    amount,
    status,
    invoice_date,
    due_date
):
    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
            "<b>FINANCE ASSISTANT</b>",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            "Professional Invoice",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 25)
    )

    invoice_details = [
        ["Invoice Number", invoice_number],
        ["Client", client],
        ["Invoice Date", invoice_date or "—"],
        ["Due Date", due_date or "—"],
        ["Status", status],
    ]

    details_table = Table(
        invoice_details,
        colWidths=[150, 300]
    )

    details_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.HexColor("#F1F3F5")
            ),
            (
                "FONTNAME",
                (0, 0),
                (0, -1),
                "Helvetica-Bold"
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.grey
            ),
            (
                "PADDING",
                (0, 0),
                (-1, -1),
                10
            ),
        ])
    )

    content.append(details_table)

    content.append(
        Spacer(1, 30)
    )

    amount_table = Table(
        [
            ["Description", "Amount"],
            [
                "Invoice Amount",
                f"PKR {amount:,.2f}"
            ]
        ],
        colWidths=[300, 150]
    )

    amount_table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#212529")
            ),
            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.white
            ),
            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.grey
            ),
            (
                "ALIGN",
                (1, 0),
                (1, -1),
                "RIGHT"
            ),
            (
                "PADDING",
                (0, 0),
                (-1, -1),
                10
            ),
        ])
    )

    content.append(amount_table)

    content.append(
        Spacer(1, 35)
    )

    content.append(
        Paragraph(
            "Generated by Finance Assistant",
            styles["Normal"]
        )
    )

    document.build(content)

    buffer.seek(0)

    return buffer


# --------------------------------------------------
# PAGE
# --------------------------------------------------

def show_invoices_page():

    # Automatically update overdue invoices
    update_overdue_invoices()

    st.title("Invoices")

    st.caption(
        "Create, manage, track payments and monitor due dates."
    )

    clients = get_clients()

    if not clients:
        st.warning(
            "Add at least one client before creating an invoice."
        )
        return

    client_names = [
        client[1]
        for client in clients
    ]

    # --------------------------------------------------
    # CREATE INVOICE
    # --------------------------------------------------

    with st.expander(
        "Create New Invoice",
        expanded=False
    ):

        with st.form("invoice_form"):

            invoice_number = st.text_input(
                "Invoice Number"
            )

            client = st.selectbox(
                "Client",
                client_names
            )

            amount = st.number_input(
                "Amount",
                min_value=0.0,
                step=100.0
            )

            date_col1, date_col2 = st.columns(2)

            with date_col1:
                invoice_date_value = st.date_input(
                    "Invoice Date",
                    value=date.today()
                )

            with date_col2:
                due_date_value = st.date_input(
                    "Due Date",
                    value=date.today()
                )

            status = st.selectbox(
                "Status",
                [
                    "Draft",
                    "Pending",
                    "Paid",
                    "Overdue",
                    "Hold",
                    "Approved",
                    "Rejected"
                ]
            )

            submitted = st.form_submit_button(
                "Save Invoice",
                type="primary"
            )

            if submitted:

                cleaned_number = invoice_number.strip()

                if not cleaned_number:
                    st.error(
                        "Invoice number is required."
                    )

                elif amount <= 0:
                    st.error(
                        "Invoice amount must be greater than zero."
                    )

                elif due_date_value < invoice_date_value:
                    st.error(
                        "Due date cannot be before the invoice date."
                    )

                elif invoice_exists(cleaned_number):
                    st.error(
                        "An invoice with this number already exists."
                    )

                else:

                    add_invoice(
                        cleaned_number,
                        client,
                        amount,
                        status,
                        invoice_date_value.isoformat(),
                        due_date_value.isoformat()
                    )

                    st.success(
                        "Invoice saved successfully."
                    )

                    st.balloons()
                    st.rerun()

    st.divider()

    # --------------------------------------------------
    # INVOICE MANAGEMENT
    # --------------------------------------------------

    st.subheader("Invoice Management")

    invoices = get_invoice_details()

    if not invoices:
        st.info("No invoices yet.")
        return

    # --------------------------------------------------
    # SEARCH + FILTER
    # --------------------------------------------------

    col1, col2 = st.columns(2)

    with col1:
        search = st.text_input(
            "Search",
            placeholder="Invoice number or client..."
        )

    statuses = sorted(
        {
            invoice[3]
            for invoice in invoices
        }
    )

    with col2:
        status_filter = st.selectbox(
            "Status Filter",
            ["All"] + statuses
        )

    filtered_invoices = []

    for invoice in invoices:

        number = str(invoice[0])
        client = str(invoice[1])
        status = str(invoice[3])

        matches_search = (
            search.lower() in number.lower()
            or search.lower() in client.lower()
        )

        matches_status = (
            status_filter == "All"
            or status == status_filter
        )

        if matches_search and matches_status:
            filtered_invoices.append(invoice)

    st.caption(
        f"{len(filtered_invoices)} invoice(s) found."
    )

    # --------------------------------------------------
    # INVOICE CARDS
    # --------------------------------------------------

    for invoice in filtered_invoices:

        invoice_number = invoice[0]
        client = invoice[1]
        amount = invoice[2]
        status = invoice[3]
        invoice_date = invoice[4]
        due_date = invoice[5]

        due_message = get_due_message(
            due_date,
            status
        )

        with st.expander(
            f"{invoice_number} — {client} — "
            f"PKR {amount:,.2f} — {due_message}"
        ):

            info1, info2, info3, info4 = st.columns(4)

            with info1:
                st.metric(
                    "Amount",
                    f"PKR {amount:,.2f}"
                )

            with info2:
                st.metric(
                    "Status",
                    status
                )

            with info3:
                st.metric(
                    "Due",
                    due_message
                )

            with info4:
                st.write("**Client**")
                st.write(client)

            # ------------------------------------------
            # DATE INFORMATION
            # ------------------------------------------

            st.divider()

            st.markdown("### Invoice Dates")

            date1, date2 = st.columns(2)

            current_invoice_date = (
                parse_date(invoice_date)
                or date.today()
            )

            current_due_date = (
                parse_date(due_date)
                or current_invoice_date
            )

            with date1:
                edited_invoice_date = st.date_input(
                    "Invoice Date",
                    value=current_invoice_date,
                    key=f"invoice_date_{invoice_number}"
                )

            with date2:
                edited_due_date = st.date_input(
                    "Due Date",
                    value=current_due_date,
                    key=f"due_date_{invoice_number}"
                )

            if st.button(
                "Update Dates",
                key=f"dates_{invoice_number}"
            ):

                if edited_due_date < edited_invoice_date:

                    st.error(
                        "Due date cannot be before invoice date."
                    )

                else:

                    update_invoice_dates(
                        invoice_number,
                        edited_invoice_date.isoformat(),
                        edited_due_date.isoformat()
                    )

                    st.success(
                        "Invoice dates updated."
                    )

                    st.rerun()

            # ------------------------------------------
            # DUE DATE ALERT
            # ------------------------------------------

            due_object = parse_date(due_date)

            if (
                due_object
                and status != "Paid"
            ):

                days_remaining = (
                    due_object - date.today()
                ).days

                if days_remaining < 0:

                    st.error(
                        f"Payment is {abs(days_remaining)} "
                        f"day(s) overdue."
                    )

                elif days_remaining == 0:

                    st.warning(
                        "Payment is due today."
                    )

                elif days_remaining <= 7:

                    st.warning(
                        f"Payment is due in "
                        f"{days_remaining} day(s)."
                    )

                else:

                    st.info(
                        f"Payment due in "
                        f"{days_remaining} days."
                    )

            st.divider()

            # ------------------------------------------
            # STATUS UPDATE
            # ------------------------------------------

            status_options = [
                "Draft",
                "Pending",
                "Approved",
                "Hold",
                "Paid",
                "Overdue",
                "Rejected"
            ]

            if status in status_options:
                current_index = status_options.index(
                    status
                )
            else:
                current_index = 0

            new_status = st.selectbox(
                "Change Status",
                status_options,
                index=current_index,
                key=f"status_{invoice_number}"
            )

            if st.button(
                "Update Status",
                key=f"update_{invoice_number}"
            ):

                update_invoice_status(
                    invoice_number,
                    new_status
                )

                st.success(
                    f"{invoice_number} updated to {new_status}."
                )

                st.rerun()

            # ------------------------------------------
            # PAYMENT TRACKING
            # ------------------------------------------

            st.divider()

            st.markdown("### Payment Tracking")

            total_paid = get_total_paid_for_invoice(
                invoice_number
            )

            remaining_balance = max(
                amount - total_paid,
                0
            )

            if total_paid <= 0:
                payment_state = "Unpaid"

            elif total_paid < amount:
                payment_state = "Partially Paid"

            else:
                payment_state = "Paid"

            pay1, pay2, pay3 = st.columns(3)

            with pay1:
                st.metric(
                    "Paid",
                    f"PKR {total_paid:,.2f}"
                )

            with pay2:
                st.metric(
                    "Remaining",
                    f"PKR {remaining_balance:,.2f}"
                )

            with pay3:
                st.metric(
                    "Payment State",
                    payment_state
                )

            # ------------------------------------------
            # RECORD PAYMENT
            # ------------------------------------------

            if remaining_balance > 0:

                with st.form(
                    f"payment_form_{invoice_number}"
                ):

                    payment_amount = st.number_input(
                        "Payment Amount",
                        min_value=0.0,
                        max_value=float(
                            remaining_balance
                        ),
                        step=100.0,
                        key=f"payment_amount_{invoice_number}"
                    )

                    payment_note = st.text_input(
                        "Payment Note",
                        placeholder="e.g. Bank transfer",
                        key=f"payment_note_{invoice_number}"
                    )

                    payment_submitted = (
                        st.form_submit_button(
                            "Record Payment",
                            type="primary"
                        )
                    )

                    if payment_submitted:

                        if payment_amount <= 0:

                            st.error(
                                "Payment must be greater than zero."
                            )

                        else:

                            if (
                                total_paid + payment_amount
                                >= amount
                            ):
                                new_payment_status = "Paid"

                            else:
                                new_payment_status = (
                                    "Partially Paid"
                                )

                            add_payment_event(
                                invoice_number,
                                new_payment_status,
                                payment_amount,
                                payment_note
                            )

                            if new_payment_status == "Paid":

                                update_invoice_status(
                                    invoice_number,
                                    "Paid"
                                )

                            st.success(
                                f"Payment of PKR "
                                f"{payment_amount:,.2f} recorded."
                            )

                            st.rerun()

            else:

                st.success(
                    "Invoice has been fully paid."
                )

            # ------------------------------------------
            # PAYMENT HISTORY
            # ------------------------------------------

            payment_events = get_payment_events(
                invoice_number
            )

            if payment_events:

                st.markdown(
                    "#### Payment History"
                )

                payment_history = []

                for event in payment_events:

                    payment_history.append({
                        "Amount": (
                            f"PKR {event[2]:,.2f}"
                        ),
                        "Status": event[1],
                        "Note": (
                            event[3]
                            if event[3]
                            else "—"
                        ),
                        "Recorded": event[4]
                    })

                st.dataframe(
                    payment_history,
                    use_container_width=True,
                    hide_index=True
                )

            # ------------------------------------------
            # PDF
            # ------------------------------------------

            st.divider()

            pdf = generate_invoice_pdf(
                invoice_number,
                client,
                amount,
                status,
                invoice_date,
                due_date
            )

            st.download_button(
                "Download PDF Invoice",
                data=pdf,
                file_name=f"{invoice_number}.pdf",
                mime="application/pdf",
                key=f"pdf_{invoice_number}"
            )