import os
from datetime import datetime, date

import psycopg
from psycopg_pool import ConnectionPool
from dotenv import load_dotenv


# --------------------------------------------------
# ENVIRONMENT / CONNECTION
# --------------------------------------------------

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL was not found. "
        "Make sure it exists in your .env file."
    )

POOL = ConnectionPool(
    conninfo=DATABASE_URL,
    min_size=1,
    max_size=5,
    timeout=30,
    kwargs={
        "autocommit": True
    },
    open=True
)


def get_connection():
    return POOL.connection()


# --------------------------------------------------
# INITIAL SETUP
# --------------------------------------------------

def create_tables():
    create_clients_table()
    create_invoice_table()
    create_review_decisions_table()
    create_payment_events_table()
    create_reminder_events_table()


def create_clients_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS clients(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company TEXT NOT NULL,
                    email TEXT,
                    phone TEXT
                )
            """)


def create_invoice_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS invoices(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT,
                    client TEXT,
                    amount DOUBLE PRECISION,
                    status TEXT,
                    invoice_date TEXT,
                    due_date TEXT
                )
            """)


def create_review_decisions_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS review_decisions(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    client TEXT,
                    amount DOUBLE PRECISION,
                    risk_score INTEGER,
                    detected_issue TEXT,
                    ai_summary TEXT,
                    ai_recommendation TEXT,
                    decision TEXT NOT NULL,
                    decision_reason TEXT,
                    decided_at TEXT NOT NULL
                )
            """)


def create_payment_events_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS payment_events(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    payment_status TEXT NOT NULL,
                    amount_paid DOUBLE PRECISION DEFAULT 0,
                    note TEXT,
                    recorded_at TEXT NOT NULL
                )
            """)


def create_reminder_events_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS reminder_events(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    reminder_type TEXT NOT NULL,
                    message TEXT,
                    status TEXT NOT NULL,
                    recorded_at TEXT NOT NULL
                )
            """)


# --------------------------------------------------
# CLIENTS
# --------------------------------------------------

def add_client(company, email, phone):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO clients
                (company, email, phone)
                VALUES (%s, %s, %s)
                """,
                (
                    company,
                    email,
                    phone
                )
            )


def get_clients():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT id, company, email, phone
                FROM clients
                ORDER BY company
            """)

            return cursor.fetchall()


def update_client(
    client_id,
    company,
    email,
    phone
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE clients
                SET company = %s,
                    email = %s,
                    phone = %s
                WHERE id = %s
                """,
                (
                    company,
                    email,
                    phone,
                    client_id
                )
            )


# --------------------------------------------------
# INVOICES
# --------------------------------------------------

def add_invoice(
    invoice_number,
    client,
    amount,
    status,
    invoice_date=None,
    due_date=None
):
    if invoice_date is None:
        invoice_date = date.today().isoformat()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO invoices(
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                )
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                )
            )


def get_invoices():
    """
    Keep existing 4-column structure so Dashboard,
    Smart Import and current invoice code do not break.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status
                FROM invoices
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def get_invoice_details():
    """
    Extended invoice data for newer features.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                FROM invoices
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def update_invoice_status(
    invoice_number,
    status
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET status = %s
                WHERE invoice_number = %s
                """,
                (
                    status,
                    invoice_number
                )
            )


def update_invoice_dates(
    invoice_number,
    invoice_date,
    due_date
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET invoice_date = %s,
                    due_date = %s
                WHERE invoice_number = %s
                """,
                (
                    invoice_date,
                    due_date,
                    invoice_number
                )
            )


def invoice_exists(invoice_number):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1
                FROM invoices
                WHERE LOWER(invoice_number) = LOWER(%s)
                LIMIT 1
                """,
                (invoice_number,)
            )

            return cursor.fetchone() is not None


def update_overdue_invoices():
    """
    Automatically marks unpaid invoices overdue
    once their due date has passed.
    """

    today = date.today().isoformat()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET status = 'Overdue'
                WHERE due_date IS NOT NULL
                AND due_date != ''
                AND due_date < %s
                AND status NOT IN (
                    'Paid',
                    'Rejected',
                    'Hold'
                )
                """,
                (today,)
            )


def get_overdue_invoices():
    update_overdue_invoices()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                FROM invoices
                WHERE status = 'Overdue'
                ORDER BY due_date ASC
            """)

            return cursor.fetchall()


# --------------------------------------------------
# REVIEW DECISIONS
# --------------------------------------------------

def add_review_decision(
    invoice_number,
    client,
    amount,
    risk_score,
    detected_issue,
    ai_summary,
    ai_recommendation,
    decision,
    decision_reason
):
    decided_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO review_decisions(
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                )
                VALUES (
                    %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s
                )
                """,
                (
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                )
            )


def get_review_decisions():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                FROM review_decisions
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def get_review_decision_for_invoice(
    invoice_number
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                FROM review_decisions
                WHERE invoice_number = %s
                ORDER BY id DESC
                LIMIT 1
                """,
                (invoice_number,)
            )

            return cursor.fetchone()


# --------------------------------------------------
# PAYMENT TRACKING
# --------------------------------------------------

def add_payment_event(
    invoice_number,
    payment_status,
    amount_paid,
    note
):
    recorded_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO payment_events(
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                )
            )


def get_payment_events(
    invoice_number=None
):
    with get_connection() as conn:
        with conn.cursor() as cursor:

            if invoice_number:
                cursor.execute(
                    """
                    SELECT
                        invoice_number,
                        payment_status,
                        amount_paid,
                        note,
                        recorded_at
                    FROM payment_events
                    WHERE invoice_number = %s
                    ORDER BY id DESC
                    """,
                    (invoice_number,)
                )

            else:
                cursor.execute("""
                    SELECT
                        invoice_number,
                        payment_status,
                        amount_paid,
                        note,
                        recorded_at
                    FROM payment_events
                    ORDER BY id DESC
                """)

            return cursor.fetchall()


def get_total_paid_for_invoice(
    invoice_number
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT COALESCE(
                    SUM(amount_paid),
                    0
                )
                FROM payment_events
                WHERE invoice_number = %s
                """,
                (invoice_number,)
            )

            return cursor.fetchone()[0]


# --------------------------------------------------
# PAYMENT REMINDERS
# --------------------------------------------------

def get_reminder_queue():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.due_date,
                    i.status,
                    c.email,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid
                FROM invoices i
                LEFT JOIN clients c
                    ON i.client = c.company
                LEFT JOIN payment_events p
                    ON i.invoice_number = p.invoice_number
                GROUP BY
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.due_date,
                    i.status,
                    c.email
            """)

            rows = cursor.fetchall()

    from datetime import date, timedelta

    today = date.today()
    queue = []

    for row in rows:
        invoice_number = row[0]
        client = row[1]
        amount = float(row[2] or 0)
        due_date = row[3]
        status = row[4]
        email = row[5]
        total_paid = float(row[6] or 0)

        remaining = max(amount - total_paid, 0)

        # Nothing to chase if already fully paid
        if remaining <= 0:
            continue

        if not due_date:
            continue

        # PostgreSQL may already return a date object
        if isinstance(due_date, str):
            due_date = date.fromisoformat(due_date)

        if due_date < today:
            reminder_type = "Overdue"

        elif due_date == today:
            reminder_type = "Due Today"

        elif due_date <= today + timedelta(days=3):
            reminder_type = "Due Soon"

        else:
            continue

        queue.append({
            "invoice_number": invoice_number,
            "client": client,
            "email": email,
            "amount": amount,
            "remaining": remaining,
            "due_date": due_date.isoformat(),
            "status": status,
            "reminder_type": reminder_type,
        })

    return queue

def add_reminder_event(
    invoice_number,
    reminder_type,
    message,
    status="Prepared"
):
    recorded_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO reminder_events(
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                )
            )


def get_reminder_events():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                FROM reminder_events
                ORDER BY id DESC
            """)

            return cursor.fetchall()
def get_invoice_management_data():
    """
    Fetch invoices and total payments in one database query.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.status,
                    i.invoice_date,
                    i.due_date,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid
                FROM invoices i
                LEFT JOIN payment_events p
                    ON p.invoice_number = i.invoice_number
                GROUP BY
                    i.id,
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.status,
                    i.invoice_date,
                    i.due_date
                ORDER BY i.id DESC
            """)

            return cursor.fetchall()


def get_all_payment_events_grouped():
    """
    Fetch all payment history once and group it by invoice.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                FROM payment_events
                ORDER BY id DESC
            """)

            rows = cursor.fetchall()

    grouped = {}

    for row in rows:
        invoice_number = row[0]

        if invoice_number not in grouped:
            grouped[invoice_number] = []

        grouped[invoice_number].append(row)

    return grouped