import os
from datetime import datetime, date

import psycopg
from psycopg_pool import ConnectionPool
from dotenv import load_dotenv


# --------------------------------------------------
# ENVIRONMENT / CONNECTION
# --------------------------------------------------

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL was not found. "
        "Make sure it exists in your .env file."
    )

POOL = ConnectionPool(
    conninfo=DATABASE_URL,
    min_size=1,
    max_size=5,
    timeout=30,
    kwargs={
        "autocommit": True
    },
    open=True
)


def get_connection():
    return POOL.connection()


# --------------------------------------------------
# INITIAL SETUP
# --------------------------------------------------

def create_tables():
    create_clients_table()
    create_invoice_table()
    create_review_decisions_table()
    create_payment_events_table()
    create_reminder_events_table()
    create_transactions_table()
    create_category_rules_table()


def create_clients_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS clients(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company TEXT NOT NULL,
                    email TEXT,
                    phone TEXT
                )
            """)


def create_invoice_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS invoices(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT,
                    client TEXT,
                    amount DOUBLE PRECISION,
                    status TEXT,
                    invoice_date TEXT,
                    due_date TEXT
                )
            """)


def create_review_decisions_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS review_decisions(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    client TEXT,
                    amount DOUBLE PRECISION,
                    risk_score INTEGER,
                    detected_issue TEXT,
                    ai_summary TEXT,
                    ai_recommendation TEXT,
                    decision TEXT NOT NULL,
                    decision_reason TEXT,
                    decided_at TEXT NOT NULL
                )
            """)


def create_payment_events_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS payment_events(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    payment_status TEXT NOT NULL,
                    amount_paid DOUBLE PRECISION DEFAULT 0,
                    note TEXT,
                    recorded_at TEXT NOT NULL
                )
            """)

def create_transactions_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS transactions(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                    transaction_date DATE NOT NULL,

                    transaction_type TEXT NOT NULL,

                    description TEXT,

                    amount DOUBLE PRECISION NOT NULL,

                    category TEXT DEFAULT 'Uncategorized',

                    account TEXT DEFAULT 'Manual',

                    reference TEXT,

                    source TEXT DEFAULT 'Manual',

                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)




def create_category_rules_table():
    """
    Stores user-confirmed categorization rules.
    A normalized description can therefore be remembered on future imports.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS category_rules(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    description_key TEXT UNIQUE NOT NULL,
                    category TEXT NOT NULL,
                    times_used INTEGER DEFAULT 1,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)


def normalize_transaction_description(description):
    """
    Normalize descriptions before rule matching.
    Keeps V1 deterministic and avoids AI-made-up classifications.
    """
    text = str(description or "").strip().lower()
    text = " ".join(text.split())
    return text


DEFAULT_CATEGORY_RULES = {
    "Inventory": (
        "inventory", "stock", "supplier", "wholesale",
        "cash & carry", "cash and carry"
    ),
    "Utilities": (
        "lesco", "iesco", "k-electric", "kelectric",
        "electricity", "gas bill", "sui gas", "water bill"
    ),
    "Marketing": (
        "meta ads", "facebook ads", "instagram ads",
        "google ads", "advertising", "marketing"
    ),
    "Rent": (
        "rent", "office rent", "shop rent"
    ),
    "Payroll": (
        "salary", "payroll", "wages"
    ),
    "Transport": (
        "fuel", "petrol", "diesel", "uber", "careem",
        "indrive", "transport"
    ),
    "Bank Fees": (
        "bank fee", "bank charges", "service charge",
        "transaction fee"
    ),
    "Sales": (
        "sale", "sales", "customer payment",
        "invoice payment"
    ),
}


def get_learned_category(description):
    description_key = normalize_transaction_description(description)

    if not description_key:
        return None

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT category
                FROM category_rules
                WHERE description_key = %s
                LIMIT 1
                """,
                (description_key,)
            )
            row = cursor.fetchone()

    return row[0] if row else None


def categorize_transaction(description, transaction_type=None):
    """
    Smart Categorization V1:
    1. Exact user-learned rule
    2. Deterministic keyword rules
    3. Uncategorized when uncertain

    No LLM is allowed to invent a category in this layer.
    """
    description_key = normalize_transaction_description(description)

    if not description_key:
        return "Uncategorized"

    learned = get_learned_category(description_key)
    if learned:
        return learned

    for category, keywords in DEFAULT_CATEGORY_RULES.items():
        if any(keyword in description_key for keyword in keywords):
            return category

    if str(transaction_type or "").strip().lower() == "income":
        return "Income"

    return "Uncategorized"


def remember_category_correction(description, category):
    """
    Save a user's correction and apply it to matching existing transactions.
    """
    description_key = normalize_transaction_description(description)
    category = str(category or "").strip()

    if not description_key:
        raise ValueError("Description is required to remember a category.")

    if not category:
        raise ValueError("Category is required.")

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO category_rules(
                    description_key,
                    category,
                    times_used,
                    updated_at
                )
                VALUES (%s, %s, 1, CURRENT_TIMESTAMP)
                ON CONFLICT (description_key)
                DO UPDATE SET
                    category = EXCLUDED.category,
                    times_used = category_rules.times_used + 1,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (description_key, category)
            )

            cursor.execute(
                """
                UPDATE transactions
                SET category = %s
                WHERE LOWER(
                    REGEXP_REPLACE(
                        TRIM(COALESCE(description, '')),
                        '\\s+',
                        ' ',
                        'g'
                    )
                ) = %s
                """,
                (category, description_key)
            )


def update_transaction_category(
    transaction_id,
    category,
    learn_from_correction=True
):
    """
    Correct one transaction. By default the correction becomes a learned rule.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT description
                FROM transactions
                WHERE id = %s
                """,
                (transaction_id,)
            )
            row = cursor.fetchone()

            if not row:
                return False

            description = row[0]

            cursor.execute(
                """
                UPDATE transactions
                SET category = %s
                WHERE id = %s
                """,
                (category, transaction_id)
            )

    if learn_from_correction:
        remember_category_correction(description, category)

    return True


def get_category_rules():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    description_key,
                    category,
                    times_used,
                    updated_at
                FROM category_rules
                ORDER BY updated_at DESC, id DESC
            """)
            return cursor.fetchall()


def add_transaction(
    transaction_date,
    transaction_type,
    description,
    amount,
    category="Uncategorized",
    account="Manual",
    reference=None,
    source="Manual"
):
    if not category or str(category).strip().lower() == "uncategorized":
        category = categorize_transaction(
            description,
            transaction_type
        )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO transactions(
                    transaction_date,
                    transaction_type,
                    description,
                    amount,
                    category,
                    account,
                    reference,
                    source
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    transaction_date,
                    transaction_type,
                    description,
                    float(amount),
                    category,
                    account,
                    reference,
                    source
                )
            )


def get_transactions():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    id,
                    transaction_date,
                    transaction_type,
                    description,
                    amount,
                    category,
                    account,
                    reference,
                    source,
                    created_at
                FROM transactions
                ORDER BY transaction_date DESC, id DESC
                """
            )

            return cursor.fetchall()


def get_transaction_summary():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'income'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS total_income,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'expense'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS total_expenses

                FROM transactions
                """
            )

            result = cursor.fetchone()

            total_income = float(result[0] or 0)
            total_expenses = float(result[1] or 0)

            return {
                "income": total_income,
                "expenses": total_expenses,
                "net": total_income - total_expenses
            }


def create_reminder_events_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS reminder_events(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    reminder_type TEXT NOT NULL,
                    message TEXT,
                    status TEXT NOT NULL,
                    recorded_at TEXT NOT NULL
                )
            """)


# --------------------------------------------------
# CLIENTS
# --------------------------------------------------

def add_client(company, email, phone):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO clients
                (company, email, phone)
                VALUES (%s, %s, %s)
                """,
                (
                    company,
                    email,
                    phone
                )
            )


def get_clients():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT id, company, email, phone
                FROM clients
                ORDER BY company
            """)

            return cursor.fetchall()


def update_client(
    client_id,
    company,
    email,
    phone
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE clients
                SET company = %s,
                    email = %s,
                    phone = %s
                WHERE id = %s
                """,
                (
                    company,
                    email,
                    phone,
                    client_id
                )
            )


# --------------------------------------------------
# INVOICES
# --------------------------------------------------

def add_invoice(
    invoice_number,
    client,
    amount,
    status,
    invoice_date=None,
    due_date=None
):
    if invoice_date is None:
        invoice_date = date.today().isoformat()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO invoices(
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                )
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                )
            )


def get_invoices():
    """
    Keep existing 4-column structure so Dashboard,
    Smart Import and current invoice code do not break.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status
                FROM invoices
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def get_invoice_details():
    """
    Extended invoice data for newer features.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                FROM invoices
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def update_invoice_status(
    invoice_number,
    status
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET status = %s
                WHERE invoice_number = %s
                """,
                (
                    status,
                    invoice_number
                )
            )


def update_invoice_dates(
    invoice_number,
    invoice_date,
    due_date
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET invoice_date = %s,
                    due_date = %s
                WHERE invoice_number = %s
                """,
                (
                    invoice_date,
                    due_date,
                    invoice_number
                )
            )


def invoice_exists(invoice_number):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1
                FROM invoices
                WHERE LOWER(invoice_number) = LOWER(%s)
                LIMIT 1
                """,
                (invoice_number,)
            )

            return cursor.fetchone() is not None


def update_overdue_invoices():
    """
    Automatically marks unpaid invoices overdue
    once their due date has passed.
    """

    today = date.today().isoformat()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET status = 'Overdue'
                WHERE due_date IS NOT NULL
                AND due_date != ''
                AND due_date < %s
                AND status NOT IN (
                    'Paid',
                    'Rejected',
                    'Hold'
                )
                """,
                (today,)
            )


def get_overdue_invoices():
    update_overdue_invoices()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                FROM invoices
                WHERE status = 'Overdue'
                ORDER BY due_date ASC
            """)

            return cursor.fetchall()


# --------------------------------------------------
# REVIEW DECISIONS
# --------------------------------------------------

def add_review_decision(
    invoice_number,
    client,
    amount,
    risk_score,
    detected_issue,
    ai_summary,
    ai_recommendation,
    decision,
    decision_reason
):
    decided_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO review_decisions(
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                )
                VALUES (
                    %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s
                )
                """,
                (
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                )
            )


def get_review_decisions():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                FROM review_decisions
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def get_review_decision_for_invoice(
    invoice_number
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                FROM review_decisions
                WHERE invoice_number = %s
                ORDER BY id DESC
                LIMIT 1
                """,
                (invoice_number,)
            )

            return cursor.fetchone()


# --------------------------------------------------
# PAYMENT TRACKING
# --------------------------------------------------

def add_payment_event(
    invoice_number,
    payment_status,
    amount_paid,
    note
):
    recorded_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO payment_events(
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                )
            )


def get_payment_events(
    invoice_number=None
):
    with get_connection() as conn:
        with conn.cursor() as cursor:

            if invoice_number:
                cursor.execute(
                    """
                    SELECT
                        invoice_number,
                        payment_status,
                        amount_paid,
                        note,
                        recorded_at
                    FROM payment_events
                    WHERE invoice_number = %s
                    ORDER BY id DESC
                    """,
                    (invoice_number,)
                )

            else:
                cursor.execute("""
                    SELECT
                        invoice_number,
                        payment_status,
                        amount_paid,
                        note,
                        recorded_at
                    FROM payment_events
                    ORDER BY id DESC
                """)

            return cursor.fetchall()


def get_total_paid_for_invoice(
    invoice_number
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT COALESCE(
                    SUM(amount_paid),
                    0
                )
                FROM payment_events
                WHERE invoice_number = %s
                """,
                (invoice_number,)
            )

            return cursor.fetchone()[0]
        
def get_payment_summary(invoice_number):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    i.amount,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid,
                    COUNT(p.id) AS payment_count,
                    MAX(p.recorded_at) AS last_payment_at
                FROM invoices i
                LEFT JOIN payment_events p
                    ON p.invoice_number = i.invoice_number
                WHERE i.invoice_number = %s
                GROUP BY i.amount
                """,
                (invoice_number,)
            )

            row = cursor.fetchone()

            if not row:
                return None

            invoice_amount = float(row[0] or 0)
            total_paid = float(row[1] or 0)

            return {
                "invoice_amount": invoice_amount,
                "total_paid": total_paid,
                "remaining": max(
                    invoice_amount - total_paid,
                    0
                ),
                "payment_count": int(row[2] or 0),
                "last_payment_at": row[3],
                "is_paid": total_paid >= invoice_amount
            }


# --------------------------------------------------
# PAYMENT REMINDERS
# --------------------------------------------------

def get_reminder_queue():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.due_date,
                    i.status,
                    c.email,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid
                FROM invoices i
                LEFT JOIN clients c
                    ON i.client = c.company
                LEFT JOIN payment_events p
                    ON i.invoice_number = p.invoice_number
                GROUP BY
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.due_date,
                    i.status,
                    c.email
            """)

            rows = cursor.fetchall()

    from datetime import date, timedelta

    today = date.today()
    queue = []

    for row in rows:
        invoice_number = row[0]
        client = row[1]
        amount = float(row[2] or 0)
        due_date = row[3]
        status = row[4]
        email = row[5]
        total_paid = float(row[6] or 0)

        remaining = max(amount - total_paid, 0)

        # Nothing to chase if already fully paid
        if remaining <= 0:
            continue

        if not due_date:
            continue

        # PostgreSQL may already return a date object
        if isinstance(due_date, str):
            due_date = date.fromisoformat(due_date)

        if due_date < today:
            reminder_type = "Overdue"

        elif due_date == today:
            reminder_type = "Due Today"

        elif due_date <= today + timedelta(days=3):
            reminder_type = "Due Soon"

        else:
            continue

        queue.append({
            "invoice_number": invoice_number,
            "client": client,
            "email": email,
            "amount": amount,
            "remaining": remaining,
            "due_date": due_date.isoformat(),
            "status": status,
            "reminder_type": reminder_type,
        })

    return queue

def add_reminder_event(
    invoice_number,
    reminder_type,
    message,
    status="Prepared"
):
    recorded_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO reminder_events(
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                )
            )


def get_reminder_events():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                FROM reminder_events
                ORDER BY id DESC
            """)

            return cursor.fetchall()
def get_invoice_management_data():
    """
    Fetch invoices and total payments in one database query.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.status,
                    i.invoice_date,
                    i.due_date,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid
                FROM invoices i
                LEFT JOIN payment_events p
                    ON p.invoice_number = i.invoice_number
                GROUP BY
                    i.id,
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.status,
                    i.invoice_date,
                    i.due_date
                ORDER BY i.id DESC
            """)

            return cursor.fetchall()


def get_all_payment_events_grouped():
    """
    Fetch all payment history once and group it by invoice.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                FROM payment_events
                ORDER BY id DESC
            """)

            rows = cursor.fetchall()

    grouped = {}

    for row in rows:
        invoice_number = row[0]

        if invoice_number not in grouped:
            grouped[invoice_number] = []

        grouped[invoice_number].append(row)

    return grouped

# --------------------------------------------------
# FINANCIAL REPORTING
# --------------------------------------------------

def get_monthly_profit_and_loss(year, month):
    """
    Returns income, expenses and net profit/loss
    for a selected month.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'income'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS income,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'expense'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS expenses

                FROM transactions

                WHERE EXTRACT(YEAR FROM transaction_date) = %s
                AND EXTRACT(MONTH FROM transaction_date) = %s
                """,
                (
                    year,
                    month
                )
            )

            row = cursor.fetchone()

            income = float(row[0] or 0)
            expenses = float(row[1] or 0)

            return {
                "income": income,
                "expenses": expenses,
                "net_profit": income - expenses
            }


def get_monthly_expense_breakdown(year, month):
    """
    Expense totals grouped by category
    for a selected month.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    category,
                    COALESCE(SUM(amount), 0) AS total

                FROM transactions

                WHERE LOWER(transaction_type) = 'expense'
                AND EXTRACT(YEAR FROM transaction_date) = %s
                AND EXTRACT(MONTH FROM transaction_date) = %s

                GROUP BY category
                ORDER BY total DESC
                """,
                (
                    year,
                    month
                )
            )

            rows = cursor.fetchall()

            return [
                {
                    "category": row[0] or "Uncategorized",
                    "amount": float(row[1] or 0)
                }
                for row in rows
            ]


def get_monthly_cash_flow():
    """
    Monthly income, expenses and net cash flow.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    DATE_TRUNC(
                        'month',
                        transaction_date
                    ) AS month,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'income'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS income,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'expense'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS expenses

                FROM transactions

                GROUP BY DATE_TRUNC(
                    'month',
                    transaction_date
                )

                ORDER BY month ASC
                """
            )

            rows = cursor.fetchall()

            result = []

            for row in rows:
                income = float(row[1] or 0)
                expenses = float(row[2] or 0)

                result.append({
                    "month": row[0],
                    "income": income,
                    "expenses": expenses,
                    "net": income - expenses
                })

            return result


def get_monthly_transaction_details(year, month):
    """
    Full transaction detail for a selected month.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    transaction_date,
                    transaction_type,
                    description,
                    amount,
                    category,
                    account,
                    reference,
                    source

                FROM transactions

                WHERE EXTRACT(YEAR FROM transaction_date) = %s
                AND EXTRACT(MONTH FROM transaction_date) = %s

                ORDER BY transaction_date DESC, id DESC
                """,
                (
                    year,
                    month
                )
            )

            return cursor.fetchall()