import os
from datetime import datetime, date

import psycopg
from psycopg_pool import ConnectionPool
from dotenv import load_dotenv


# --------------------------------------------------
# ENVIRONMENT / CONNECTION
# --------------------------------------------------

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL was not found. "
        "Make sure it exists in your .env file."
    )

POOL = ConnectionPool(
    conninfo=DATABASE_URL,
    min_size=1,
    max_size=5,
    timeout=30,
    kwargs={
        "autocommit": True
    },
    open=True
)


def get_connection():
    return POOL.connection()


# --------------------------------------------------
# INITIAL SETUP
# --------------------------------------------------

_TABLES_READY = False


def create_tables():
    global _TABLES_READY

    if _TABLES_READY:
        return

    create_clients_table()
    create_invoice_table()
    create_review_decisions_table()
    create_payment_events_table()
    create_reminder_events_table()
    create_transactions_table()
    create_category_rules_table()
    create_business_settings_table()
    create_business_categories_table()

    _TABLES_READY = True


def create_clients_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS clients(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company TEXT NOT NULL,
                    email TEXT,
                    phone TEXT
                )
            """)


def create_invoice_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS invoices(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT,
                    client TEXT,
                    amount DOUBLE PRECISION,
                    status TEXT,
                    invoice_date TEXT,
                    due_date TEXT
                )
            """)


def create_review_decisions_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS review_decisions(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    client TEXT,
                    amount DOUBLE PRECISION,
                    risk_score INTEGER,
                    detected_issue TEXT,
                    ai_summary TEXT,
                    ai_recommendation TEXT,
                    decision TEXT NOT NULL,
                    decision_reason TEXT,
                    decided_at TEXT NOT NULL
                )
            """)


def create_payment_events_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS payment_events(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    payment_status TEXT NOT NULL,
                    amount_paid DOUBLE PRECISION DEFAULT 0,
                    note TEXT,
                    recorded_at TEXT NOT NULL
                )
            """)

def create_transactions_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS transactions(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                    transaction_date DATE NOT NULL,

                    transaction_type TEXT NOT NULL,

                    description TEXT,

                    amount DOUBLE PRECISION NOT NULL,

                    category TEXT DEFAULT 'Uncategorized',

                    account TEXT DEFAULT 'Manual',

                    reference TEXT,

                    source TEXT DEFAULT 'Manual',

                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)




def create_category_rules_table():
    """
    Stores user-confirmed categorization rules.
    A normalized description can therefore be remembered on future imports.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS category_rules(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    description_key TEXT UNIQUE NOT NULL,
                    category TEXT NOT NULL,
                    times_used INTEGER DEFAULT 1,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)


def normalize_transaction_description(description):
    """
    Normalize descriptions before rule matching.
    Keeps V1 deterministic and avoids AI-made-up classifications.
    """
    text = str(description or "").strip().lower()
    text = " ".join(text.split())
    return text


DEFAULT_CATEGORY_RULES = {
    "Inventory": (
        "inventory", "stock", "supplier", "wholesale",
        "cash & carry", "cash and carry"
    ),
    "Utilities": (
        "lesco", "iesco", "k-electric", "kelectric",
        "electricity", "gas bill", "sui gas", "water bill"
    ),
    "Marketing": (
        "meta ads", "facebook ads", "instagram ads",
        "google ads", "advertising", "marketing"
    ),
    "Rent": (
        "rent", "office rent", "shop rent"
    ),
    "Payroll": (
        "salary", "payroll", "wages"
    ),
    "Transport": (
        "fuel", "petrol", "diesel", "uber", "careem",
        "indrive", "transport"
    ),
    "Bank Fees": (
        "bank fee", "bank charges", "service charge",
        "transaction fee"
    ),
    "Sales": (
        "sale", "sales", "customer payment",
        "invoice payment"
    ),
}


def get_learned_category(description):
    description_key = normalize_transaction_description(description)

    if not description_key:
        return None

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT category
                FROM category_rules
                WHERE description_key = %s
                LIMIT 1
                """,
                (description_key,)
            )
            row = cursor.fetchone()

    return row[0] if row else None


def categorize_transaction(description, transaction_type=None):
    """
    Smart Categorization V1:
    1. Exact user-learned rule
    2. Deterministic keyword rules
    3. Uncategorized when uncertain

    No LLM is allowed to invent a category in this layer.
    """
    description_key = normalize_transaction_description(description)

    if not description_key:
        return "Uncategorized"

    learned = get_learned_category(description_key)
    if learned:
        return learned

    for category, keywords in DEFAULT_CATEGORY_RULES.items():
        if any(keyword in description_key for keyword in keywords):
            return category

    if str(transaction_type or "").strip().lower() == "income":
        return "Income"

    return "Uncategorized"


def remember_category_correction(description, category):
    """
    Save a user's correction and apply it to matching existing transactions.
    """
    description_key = normalize_transaction_description(description)
    category = str(category or "").strip()

    if not description_key:
        raise ValueError("Description is required to remember a category.")

    if not category:
        raise ValueError("Category is required.")

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO category_rules(
                    description_key,
                    category,
                    times_used,
                    updated_at
                )
                VALUES (%s, %s, 1, CURRENT_TIMESTAMP)
                ON CONFLICT (description_key)
                DO UPDATE SET
                    category = EXCLUDED.category,
                    times_used = category_rules.times_used + 1,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (description_key, category)
            )

            cursor.execute(
                """
                UPDATE transactions
                SET category = %s
                WHERE LOWER(
                    REGEXP_REPLACE(
                        TRIM(COALESCE(description, '')),
                        '\\s+',
                        ' ',
                        'g'
                    )
                ) = %s
                """,
                (category, description_key)
            )


def update_transaction_category(
    transaction_id,
    category,
    learn_from_correction=True
):
    """
    Correct one transaction. By default the correction becomes a learned rule.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT description
                FROM transactions
                WHERE id = %s
                """,
                (transaction_id,)
            )
            row = cursor.fetchone()

            if not row:
                return False

            description = row[0]

            cursor.execute(
                """
                UPDATE transactions
                SET category = %s
                WHERE id = %s
                """,
                (category, transaction_id)
            )

    if learn_from_correction:
        remember_category_correction(description, category)

    return True


def get_category_rules():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    description_key,
                    category,
                    times_used,
                    updated_at
                FROM category_rules
                ORDER BY updated_at DESC, id DESC
            """)
            return cursor.fetchall()

def transaction_exists(
    transaction_date,
    transaction_type,
    description,
    amount,
    account,
    reference=None
):
    """
    Check whether a transaction has already been imported.

    If a reference exists, it is the strongest duplicate signal.
    Otherwise we compare the transaction's core fields.
    """

    description = str(description or "").strip()
    account = str(account or "").strip()
    reference = str(reference or "").strip()

    with get_connection() as conn:
        with conn.cursor() as cursor:

            # ------------------------------------------
            # BEST CASE: BANK REFERENCE EXISTS
            # ------------------------------------------

            if reference:
                cursor.execute(
                    """
                    SELECT 1
                    FROM transactions
                    WHERE transaction_date = %s
                    AND LOWER(COALESCE(account, '')) = LOWER(%s)
                    AND LOWER(COALESCE(reference, '')) = LOWER(%s)
                    LIMIT 1
                    """,
                    (
                        transaction_date,
                        account,
                        reference
                    )
                )

                if cursor.fetchone():
                    return True

            # ------------------------------------------
            # FALLBACK: MATCH CORE TRANSACTION DETAILS
            # ------------------------------------------

            cursor.execute(
                """
                SELECT 1
                FROM transactions
                WHERE transaction_date = %s
                AND LOWER(transaction_type) = LOWER(%s)
                AND LOWER(TRIM(COALESCE(description, '')))
                    = LOWER(TRIM(%s))
                AND ABS(amount - %s) < 0.01
                AND LOWER(TRIM(COALESCE(account, '')))
                    = LOWER(TRIM(%s))
                LIMIT 1
                """,
                (
                    transaction_date,
                    transaction_type,
                    description,
                    float(amount),
                    account
                )
            )

            return cursor.fetchone() is not None
        
def add_transaction(
    transaction_date,
    transaction_type,
    description,
    amount,
    category="Uncategorized",
    account="Manual",
    reference=None,
    source="Manual"
):
    if not category or str(category).strip().lower() == "uncategorized":
        category = categorize_transaction(
            description,
            transaction_type
        )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO transactions(
                    transaction_date,
                    transaction_type,
                    description,
                    amount,
                    category,
                    account,
                    reference,
                    source
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    transaction_date,
                    transaction_type,
                    description,
                    float(amount),
                    category,
                    account,
                    reference,
                    source
                )
            )


def get_transactions():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    id,
                    transaction_date,
                    transaction_type,
                    description,
                    amount,
                    category,
                    account,
                    reference,
                    source,
                    created_at
                FROM transactions
                ORDER BY transaction_date DESC, id DESC
                """
            )

            return cursor.fetchall()


def get_transaction_summary():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'income'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS total_income,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'expense'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS total_expenses

                FROM transactions
                """
            )

            result = cursor.fetchone()

            total_income = float(result[0] or 0)
            total_expenses = float(result[1] or 0)

            return {
                "income": total_income,
                "expenses": total_expenses,
                "net": total_income - total_expenses
            }


def create_reminder_events_table():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS reminder_events(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_number TEXT NOT NULL,
                    reminder_type TEXT NOT NULL,
                    message TEXT,
                    status TEXT NOT NULL,
                    recorded_at TEXT NOT NULL
                )
            """)

# --------------------------------------------------
# BUSINESS SETTINGS
# --------------------------------------------------

BUSINESS_TYPES = [
    "Retail / Boutique",
    "Salon / Beauty",
    "Tutoring / Education",
    "Restaurant / Food",
    "Professional Services",
    "Wholesale / Distribution",
    "E-commerce",
    "Other",
]

INDUSTRY_CATEGORY_DEFAULTS = {
    "Retail / Boutique": {
        "Income": ["Sales", "Other Income"],
        "Expense": [
            "Inventory",
            "Packaging",
            "Delivery",
            "Marketing",
            "Rent",
            "Utilities",
            "Payroll",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
    "Salon / Beauty": {
        "Income": ["Services", "Product Sales", "Other Income"],
        "Expense": [
            "Beauty Supplies",
            "Staff Payments",
            "Rent",
            "Utilities",
            "Marketing",
            "Laundry",
            "Transport",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
    "Tutoring / Education": {
        "Income": ["Student Fees", "Course Sales", "Other Income"],
        "Expense": [
            "Teacher Payments",
            "Rent",
            "Utilities",
            "Educational Materials",
            "Marketing",
            "Software",
            "Transport",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
    "Restaurant / Food": {
        "Income": ["Food Sales", "Delivery Sales", "Other Income"],
        "Expense": [
            "Ingredients",
            "Packaging",
            "Delivery",
            "Payroll",
            "Rent",
            "Utilities",
            "Marketing",
            "Equipment",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
    "Professional Services": {
        "Income": ["Services", "Consulting", "Other Income"],
        "Expense": [
            "Payroll",
            "Rent",
            "Utilities",
            "Software",
            "Marketing",
            "Travel",
            "Office Supplies",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
    "Wholesale / Distribution": {
        "Income": ["Sales", "Other Income"],
        "Expense": [
            "Inventory",
            "Freight",
            "Warehousing",
            "Transport",
            "Payroll",
            "Rent",
            "Utilities",
            "Marketing",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
    "E-commerce": {
        "Income": ["Online Sales", "Other Income"],
        "Expense": [
            "Inventory",
            "Packaging",
            "Courier",
            "Marketplace Fees",
            "Marketing",
            "Software",
            "Returns",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
    "Other": {
        "Income": ["Sales", "Services", "Other Income"],
        "Expense": [
            "Inventory",
            "Rent",
            "Utilities",
            "Payroll",
            "Transport",
            "Marketing",
            "Office",
            "Bank Fees",
            "Taxes",
            "Other Expense",
        ],
    },
}


def create_business_settings_table():
    """
    Create and safely upgrade the single-business settings table.
    Existing values are preserved.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS business_settings(
                    id INTEGER PRIMARY KEY,
                    business_name TEXT DEFAULT '',
                    business_type TEXT DEFAULT 'Other',
                    business_email TEXT DEFAULT '',
                    business_phone TEXT DEFAULT '',
                    business_address TEXT DEFAULT '',
                    currency TEXT DEFAULT 'PKR',
                    timezone TEXT DEFAULT 'Asia/Karachi',
                    payment_terms INTEGER DEFAULT 30,
                    invoice_prefix TEXT DEFAULT 'INV',
                    tax_rate DOUBLE PRECISION DEFAULT 0,
                    reminders_enabled BOOLEAN DEFAULT TRUE,
                    reminder_days_before INTEGER DEFAULT 3,
                    overdue_reminders_enabled BOOLEAN DEFAULT TRUE,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS business_type TEXT DEFAULT 'Other'
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'Asia/Karachi'
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS payment_terms INTEGER DEFAULT 30
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS invoice_prefix TEXT DEFAULT 'INV'
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS tax_rate DOUBLE PRECISION DEFAULT 0
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS reminders_enabled BOOLEAN DEFAULT TRUE
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS reminder_days_before INTEGER DEFAULT 3
            """)

            cursor.execute("""
                ALTER TABLE business_settings
                ADD COLUMN IF NOT EXISTS overdue_reminders_enabled BOOLEAN DEFAULT TRUE
            """)

            cursor.execute("""
                INSERT INTO business_settings(
                    id,
                    business_name,
                    business_type,
                    business_email,
                    business_phone,
                    business_address,
                    currency,
                    timezone,
                    payment_terms,
                    invoice_prefix,
                    tax_rate,
                    reminders_enabled,
                    reminder_days_before,
                    overdue_reminders_enabled,
                    updated_at
                )
                VALUES (
                    1,
                    '',
                    'Other',
                    '',
                    '',
                    '',
                    'PKR',
                    'Asia/Karachi',
                    30,
                    'INV',
                    0,
                    TRUE,
                    3,
                    TRUE,
                    CURRENT_TIMESTAMP
                )
                ON CONFLICT (id) DO NOTHING
            """)


def create_business_categories_table():
    """
    Stores categories that belong to this business.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS business_categories(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    category_name TEXT NOT NULL,
                    category_type TEXT NOT NULL,
                    is_system BOOLEAN DEFAULT FALSE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(category_name, category_type)
                )
            """)


def get_business_settings():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    business_name,
                    business_type,
                    business_email,
                    business_phone,
                    business_address,
                    currency,
                    timezone,
                    payment_terms,
                    invoice_prefix,
                    tax_rate,
                    reminders_enabled,
                    reminder_days_before,
                    overdue_reminders_enabled
                FROM business_settings
                WHERE id = 1
                LIMIT 1
            """)

            row = cursor.fetchone()

    if not row:
        return {
            "business_name": "",
            "business_type": "Other",
            "email": "",
            "phone": "",
            "address": "",
            "currency": "PKR",
            "timezone": "Asia/Karachi",
            "payment_terms": 30,
            "invoice_prefix": "INV",
            "tax_rate": 0.0,
            "reminders_enabled": True,
            "reminder_days_before": 3,
            "overdue_reminders_enabled": True,
        }

    return {
        "business_name": row[0] or "",
        "business_type": row[1] or "Other",
        "email": row[2] or "",
        "phone": row[3] or "",
        "address": row[4] or "",
        "currency": row[5] or "PKR",
        "timezone": row[6] or "Asia/Karachi",
        "payment_terms": int(row[7] if row[7] is not None else 30),
        "invoice_prefix": row[8] or "INV",
        "tax_rate": float(row[9] if row[9] is not None else 0),
        "reminders_enabled": bool(
            True if row[10] is None else row[10]
        ),
        "reminder_days_before": int(
            row[11] if row[11] is not None else 3
        ),
        "overdue_reminders_enabled": bool(
            True if row[12] is None else row[12]
        ),
    }


def save_business_settings(
    business_name,
    business_type,
    email,
    phone,
    address,
    currency,
    timezone,
    payment_terms,
    invoice_prefix,
    tax_rate,
    reminders_enabled,
    reminder_days_before,
    overdue_reminders_enabled
):
    business_name = str(business_name or "").strip()
    business_type = str(business_type or "Other").strip() or "Other"
    email = str(email or "").strip()
    phone = str(phone or "").strip()
    address = str(address or "").strip()
    currency = str(currency or "PKR").strip() or "PKR"
    timezone = str(timezone or "Asia/Karachi").strip() or "Asia/Karachi"
    invoice_prefix = str(invoice_prefix or "INV").strip().upper() or "INV"

    payment_terms = max(0, int(payment_terms))
    tax_rate = max(0.0, float(tax_rate))
    reminder_days_before = max(0, int(reminder_days_before))

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO business_settings(
                    id,
                    business_name,
                    business_type,
                    business_email,
                    business_phone,
                    business_address,
                    currency,
                    timezone,
                    payment_terms,
                    invoice_prefix,
                    tax_rate,
                    reminders_enabled,
                    reminder_days_before,
                    overdue_reminders_enabled,
                    updated_at
                )
                VALUES (
                    1, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s,
                    CURRENT_TIMESTAMP
                )
                ON CONFLICT (id)
                DO UPDATE SET
                    business_name = EXCLUDED.business_name,
                    business_type = EXCLUDED.business_type,
                    business_email = EXCLUDED.business_email,
                    business_phone = EXCLUDED.business_phone,
                    business_address = EXCLUDED.business_address,
                    currency = EXCLUDED.currency,
                    timezone = EXCLUDED.timezone,
                    payment_terms = EXCLUDED.payment_terms,
                    invoice_prefix = EXCLUDED.invoice_prefix,
                    tax_rate = EXCLUDED.tax_rate,
                    reminders_enabled = EXCLUDED.reminders_enabled,
                    reminder_days_before = EXCLUDED.reminder_days_before,
                    overdue_reminders_enabled = EXCLUDED.overdue_reminders_enabled,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (
                    business_name,
                    business_type,
                    email,
                    phone,
                    address,
                    currency,
                    timezone,
                    payment_terms,
                    invoice_prefix,
                    tax_rate,
                    bool(reminders_enabled),
                    reminder_days_before,
                    bool(overdue_reminders_enabled),
                )
            )

    return get_business_settings()


def ensure_business_categories(business_type=None):
    """
    Add suggested categories if the business has no categories yet.
    """
    if not business_type:
        business_type = get_business_settings()["business_type"]

    defaults = INDUSTRY_CATEGORY_DEFAULTS.get(
        business_type,
        INDUSTRY_CATEGORY_DEFAULTS["Other"]
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT COUNT(*)
                FROM business_categories
            """)
            count = int(cursor.fetchone()[0] or 0)

            if count > 0:
                return

            for category_type, names in defaults.items():
                for name in names:
                    cursor.execute(
                        """
                        INSERT INTO business_categories(
                            category_name,
                            category_type,
                            is_system
                        )
                        VALUES (%s, %s, TRUE)
                        ON CONFLICT(category_name, category_type)
                        DO NOTHING
                        """,
                        (
                            name,
                            category_type
                        )
                    )


def get_business_categories(category_type=None):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            if category_type:
                cursor.execute(
                    """
                    SELECT
                        id,
                        category_name,
                        category_type,
                        is_system
                    FROM business_categories
                    WHERE LOWER(category_type) = LOWER(%s)
                    ORDER BY category_name
                    """,
                    (category_type,)
                )
            else:
                cursor.execute("""
                    SELECT
                        id,
                        category_name,
                        category_type,
                        is_system
                    FROM business_categories
                    ORDER BY category_type, category_name
                """)

            rows = cursor.fetchall()

    return [
        {
            "id": row[0],
            "name": row[1],
            "type": row[2],
            "is_system": bool(row[3]),
        }
        for row in rows
    ]


def add_business_category(category_name, category_type):
    category_name = str(category_name or "").strip()
    category_type = str(category_type or "").strip().title()

    if not category_name:
        raise ValueError("Category name is required.")

    if category_type not in ("Income", "Expense"):
        raise ValueError("Category type must be Income or Expense.")

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO business_categories(
                    category_name,
                    category_type,
                    is_system
                )
                VALUES (%s, %s, FALSE)
                ON CONFLICT(category_name, category_type)
                DO NOTHING
                """,
                (
                    category_name,
                    category_type
                )
            )


def update_business_category(category_id, new_name):
    new_name = str(new_name or "").strip()

    if not new_name:
        raise ValueError("Category name cannot be empty.")

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE business_categories
                SET category_name = %s
                WHERE id = %s
                """,
                (
                    new_name,
                    int(category_id)
                )
            )


def delete_business_category(category_id):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                DELETE FROM business_categories
                WHERE id = %s
                """,
                (int(category_id),)
            )


def reset_business_categories_to_industry_defaults():
    settings = get_business_settings()
    business_type = settings["business_type"]

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                DELETE FROM business_categories
            """)

    ensure_business_categories(business_type)


# --------------------------------------------------
# CLIENTS
# --------------------------------------------------

def add_client(company, email, phone):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO clients
                (company, email, phone)
                VALUES (%s, %s, %s)
                """,
                (
                    company,
                    email,
                    phone
                )
            )


def get_clients():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT id, company, email, phone
                FROM clients
                ORDER BY company
            """)

            return cursor.fetchall()


def update_client(
    client_id,
    company,
    email,
    phone
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE clients
                SET company = %s,
                    email = %s,
                    phone = %s
                WHERE id = %s
                """,
                (
                    company,
                    email,
                    phone,
                    client_id
                )
            )


# --------------------------------------------------
# INVOICES
# --------------------------------------------------

def add_invoice(
    invoice_number,
    client,
    amount,
    status,
    invoice_date=None,
    due_date=None
):
    if invoice_date is None:
        invoice_date = date.today().isoformat()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO invoices(
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                )
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                )
            )


def get_invoices():
    """
    Keep existing 4-column structure so Dashboard,
    Smart Import and current invoice code do not break.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status
                FROM invoices
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def get_invoice_details():
    """
    Extended invoice data for newer features.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                FROM invoices
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def update_invoice_status(
    invoice_number,
    status
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET status = %s
                WHERE invoice_number = %s
                """,
                (
                    status,
                    invoice_number
                )
            )


def update_invoice_dates(
    invoice_number,
    invoice_date,
    due_date
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET invoice_date = %s,
                    due_date = %s
                WHERE invoice_number = %s
                """,
                (
                    invoice_date,
                    due_date,
                    invoice_number
                )
            )


def invoice_exists(invoice_number):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1
                FROM invoices
                WHERE LOWER(invoice_number) = LOWER(%s)
                LIMIT 1
                """,
                (invoice_number,)
            )

            return cursor.fetchone() is not None


def update_overdue_invoices():
    """
    Automatically marks unpaid invoices overdue
    once their due date has passed.
    """

    today = date.today().isoformat()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE invoices
                SET status = 'Overdue'
                WHERE due_date IS NOT NULL
                AND due_date != ''
                AND due_date < %s
                AND status NOT IN (
                    'Paid',
                    'Rejected',
                    'Hold'
                )
                """,
                (today,)
            )


def get_overdue_invoices():
    update_overdue_invoices()

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    status,
                    invoice_date,
                    due_date
                FROM invoices
                WHERE status = 'Overdue'
                ORDER BY due_date ASC
            """)

            return cursor.fetchall()


# --------------------------------------------------
# REVIEW DECISIONS
# --------------------------------------------------

def add_review_decision(
    invoice_number,
    client,
    amount,
    risk_score,
    detected_issue,
    ai_summary,
    ai_recommendation,
    decision,
    decision_reason
):
    decided_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO review_decisions(
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                )
                VALUES (
                    %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s
                )
                """,
                (
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                )
            )


def get_review_decisions():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                FROM review_decisions
                ORDER BY id DESC
            """)

            return cursor.fetchall()


def get_review_decision_for_invoice(
    invoice_number
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    invoice_number,
                    client,
                    amount,
                    risk_score,
                    detected_issue,
                    ai_summary,
                    ai_recommendation,
                    decision,
                    decision_reason,
                    decided_at
                FROM review_decisions
                WHERE invoice_number = %s
                ORDER BY id DESC
                LIMIT 1
                """,
                (invoice_number,)
            )

            return cursor.fetchone()


# --------------------------------------------------
# PAYMENT TRACKING
# --------------------------------------------------

def add_payment_event(
    invoice_number,
    payment_status,
    amount_paid,
    note
):
    recorded_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO payment_events(
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                )
            )


def get_payment_events(
    invoice_number=None
):
    with get_connection() as conn:
        with conn.cursor() as cursor:

            if invoice_number:
                cursor.execute(
                    """
                    SELECT
                        invoice_number,
                        payment_status,
                        amount_paid,
                        note,
                        recorded_at
                    FROM payment_events
                    WHERE invoice_number = %s
                    ORDER BY id DESC
                    """,
                    (invoice_number,)
                )

            else:
                cursor.execute("""
                    SELECT
                        invoice_number,
                        payment_status,
                        amount_paid,
                        note,
                        recorded_at
                    FROM payment_events
                    ORDER BY id DESC
                """)

            return cursor.fetchall()


def get_total_paid_for_invoice(
    invoice_number
):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT COALESCE(
                    SUM(amount_paid),
                    0
                )
                FROM payment_events
                WHERE invoice_number = %s
                """,
                (invoice_number,)
            )

            return cursor.fetchone()[0]
        
def get_payment_summary(invoice_number):
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    i.amount,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid,
                    COUNT(p.id) AS payment_count,
                    MAX(p.recorded_at) AS last_payment_at
                FROM invoices i
                LEFT JOIN payment_events p
                    ON p.invoice_number = i.invoice_number
                WHERE i.invoice_number = %s
                GROUP BY i.amount
                """,
                (invoice_number,)
            )

            row = cursor.fetchone()

            if not row:
                return None

            invoice_amount = float(row[0] or 0)
            total_paid = float(row[1] or 0)

            return {
                "invoice_amount": invoice_amount,
                "total_paid": total_paid,
                "remaining": max(
                    invoice_amount - total_paid,
                    0
                ),
                "payment_count": int(row[2] or 0),
                "last_payment_at": row[3],
                "is_paid": total_paid >= invoice_amount
            }


# --------------------------------------------------
# PAYMENT REMINDERS
# --------------------------------------------------

def get_reminder_queue():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.due_date,
                    i.status,
                    c.email,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid
                FROM invoices i
                LEFT JOIN clients c
                    ON i.client = c.company
                LEFT JOIN payment_events p
                    ON i.invoice_number = p.invoice_number
                GROUP BY
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.due_date,
                    i.status,
                    c.email
            """)

            rows = cursor.fetchall()

    from datetime import date, timedelta

    today = date.today()
    queue = []

    for row in rows:
        invoice_number = row[0]
        client = row[1]
        amount = float(row[2] or 0)
        due_date = row[3]
        status = row[4]
        email = row[5]
        total_paid = float(row[6] or 0)

        remaining = max(amount - total_paid, 0)

        # Nothing to chase if already fully paid
        if remaining <= 0:
            continue

        if not due_date:
            continue

        # PostgreSQL may already return a date object
        if isinstance(due_date, str):
            due_date = date.fromisoformat(due_date)

        if due_date < today:
            reminder_type = "Overdue"

        elif due_date == today:
            reminder_type = "Due Today"

        elif due_date <= today + timedelta(days=3):
            reminder_type = "Due Soon"

        else:
            continue

        queue.append({
            "invoice_number": invoice_number,
            "client": client,
            "email": email,
            "amount": amount,
            "remaining": remaining,
            "due_date": due_date.isoformat(),
            "status": status,
            "reminder_type": reminder_type,
        })

    return queue

def add_reminder_event(
    invoice_number,
    reminder_type,
    message,
    status="Prepared"
):
    recorded_at = datetime.now().isoformat(
        timespec="seconds"
    )

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO reminder_events(
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                )
            )


def get_reminder_events():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    reminder_type,
                    message,
                    status,
                    recorded_at
                FROM reminder_events
                ORDER BY id DESC
            """)

            return cursor.fetchall()
def get_invoice_management_data():
    """
    Fetch invoices and total payments in one database query.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.status,
                    i.invoice_date,
                    i.due_date,
                    COALESCE(SUM(p.amount_paid), 0) AS total_paid
                FROM invoices i
                LEFT JOIN payment_events p
                    ON p.invoice_number = i.invoice_number
                GROUP BY
                    i.id,
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.status,
                    i.invoice_date,
                    i.due_date
                ORDER BY i.id DESC
            """)

            return cursor.fetchall()


def get_all_payment_events_grouped():
    """
    Fetch all payment history once and group it by invoice.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    invoice_number,
                    payment_status,
                    amount_paid,
                    note,
                    recorded_at
                FROM payment_events
                ORDER BY id DESC
            """)

            rows = cursor.fetchall()

    grouped = {}

    for row in rows:
        invoice_number = row[0]

        if invoice_number not in grouped:
            grouped[invoice_number] = []

        grouped[invoice_number].append(row)

    return grouped

# --------------------------------------------------
# FINANCIAL REPORTING
# --------------------------------------------------

def get_monthly_profit_and_loss(year, month):
    """
    Returns income, expenses and net profit/loss
    for a selected month.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'income'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS income,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'expense'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS expenses

                FROM transactions

                WHERE EXTRACT(YEAR FROM transaction_date) = %s
                AND EXTRACT(MONTH FROM transaction_date) = %s
                """,
                (
                    year,
                    month
                )
            )

            row = cursor.fetchone()

            income = float(row[0] or 0)
            expenses = float(row[1] or 0)

            return {
                "income": income,
                "expenses": expenses,
                "net_profit": income - expenses
            }


def get_monthly_expense_breakdown(year, month):
    """
    Expense totals grouped by category
    for a selected month.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    category,
                    COALESCE(SUM(amount), 0) AS total

                FROM transactions

                WHERE LOWER(transaction_type) = 'expense'
                AND EXTRACT(YEAR FROM transaction_date) = %s
                AND EXTRACT(MONTH FROM transaction_date) = %s

                GROUP BY category
                ORDER BY total DESC
                """,
                (
                    year,
                    month
                )
            )

            rows = cursor.fetchall()

            return [
                {
                    "category": row[0] or "Uncategorized",
                    "amount": float(row[1] or 0)
                }
                for row in rows
            ]


def get_monthly_cash_flow():
    """
    Monthly income, expenses and net cash flow.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    DATE_TRUNC(
                        'month',
                        transaction_date
                    ) AS month,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'income'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS income,

                    COALESCE(
                        SUM(
                            CASE
                                WHEN LOWER(transaction_type) = 'expense'
                                THEN amount
                                ELSE 0
                            END
                        ),
                        0
                    ) AS expenses

                FROM transactions

                GROUP BY DATE_TRUNC(
                    'month',
                    transaction_date
                )

                ORDER BY month ASC
                """
            )

            rows = cursor.fetchall()

            result = []

            for row in rows:
                income = float(row[1] or 0)
                expenses = float(row[2] or 0)

                result.append({
                    "month": row[0],
                    "income": income,
                    "expenses": expenses,
                    "net": income - expenses
                })

            return result


def get_monthly_transaction_details(year, month):
    """
    Full transaction detail for a selected month.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    transaction_date,
                    transaction_type,
                    description,
                    amount,
                    category,
                    account,
                    reference,
                    source

                FROM transactions

                WHERE EXTRACT(YEAR FROM transaction_date) = %s
                AND EXTRACT(MONTH FROM transaction_date) = %s

                ORDER BY transaction_date DESC, id DESC
                """,
                (
                    year,
                    month
                )
            )

            return cursor.fetchall()

# --------------------------------------------------
# AI ASSISTANT — VERIFIED FINANCIAL QUERY FUNCTIONS
# --------------------------------------------------

def get_financial_assistant_snapshot():
    """
    Return a verified business snapshot for the AI Assistant.

    All monetary values are calculated by PostgreSQL/Python from stored
    transactions, invoices and payment events. The language layer should
    explain these values, never invent or recalculate them.
    """

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    COALESCE(SUM(
                        CASE
                            WHEN LOWER(transaction_type) = 'income'
                            THEN amount
                            ELSE 0
                        END
                    ), 0),
                    COALESCE(SUM(
                        CASE
                            WHEN LOWER(transaction_type) = 'expense'
                            THEN amount
                            ELSE 0
                        END
                    ), 0)
                FROM transactions
            """)
            transaction_row = cursor.fetchone()

            cursor.execute("""
                SELECT
                    COALESCE(SUM(i.amount), 0),
                    COALESCE(SUM(payment_totals.total_paid), 0),
                    COALESCE(SUM(
                        GREATEST(
                            COALESCE(i.amount, 0)
                            - COALESCE(payment_totals.total_paid, 0),
                            0
                        )
                    ), 0),
                    COUNT(*) FILTER (
                        WHERE LOWER(COALESCE(i.status, '')) = 'overdue'
                        AND GREATEST(
                            COALESCE(i.amount, 0)
                            - COALESCE(payment_totals.total_paid, 0),
                            0
                        ) > 0
                    )
                FROM invoices i
                LEFT JOIN (
                    SELECT
                        invoice_number,
                        COALESCE(SUM(amount_paid), 0) AS total_paid
                    FROM payment_events
                    GROUP BY invoice_number
                ) payment_totals
                    ON payment_totals.invoice_number = i.invoice_number
            """)
            invoice_row = cursor.fetchone()

    income = float(transaction_row[0] or 0)
    expenses = float(transaction_row[1] or 0)

    return {
        "income": income,
        "expenses": expenses,
        "net_cash_flow": income - expenses,
        "total_invoiced": float(invoice_row[0] or 0),
        "total_collected": float(invoice_row[1] or 0),
        "total_outstanding": float(invoice_row[2] or 0),
        "overdue_invoice_count": int(invoice_row[3] or 0),
    }


def get_spending_by_category(
    category=None,
    year=None,
    month=None
):
    """
    Return verified expense totals grouped by category.

    Optional filters:
    - category: exact category name, case-insensitive
    - year: calendar year
    - month: calendar month number (1-12)
    """

    conditions = [
        "LOWER(transaction_type) = 'expense'"
    ]
    params = []

    if category:
        conditions.append(
            "LOWER(COALESCE(category, 'Uncategorized')) = LOWER(%s)"
        )
        params.append(str(category).strip())

    if year is not None:
        conditions.append(
            "EXTRACT(YEAR FROM transaction_date) = %s"
        )
        params.append(int(year))

    if month is not None:
        conditions.append(
            "EXTRACT(MONTH FROM transaction_date) = %s"
        )
        params.append(int(month))

    where_clause = " AND ".join(conditions)

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                f"""
                SELECT
                    COALESCE(category, 'Uncategorized') AS category,
                    COALESCE(SUM(amount), 0) AS total,
                    COUNT(*) AS transaction_count
                FROM transactions
                WHERE {where_clause}
                GROUP BY COALESCE(category, 'Uncategorized')
                ORDER BY total DESC
                """,
                tuple(params)
            )

            rows = cursor.fetchall()

    return [
        {
            "category": row[0],
            "amount": float(row[1] or 0),
            "transaction_count": int(row[2] or 0),
        }
        for row in rows
    ]


def get_top_expenses(
    limit=5,
    year=None,
    month=None
):
    """
    Return the largest verified expense transactions.
    """

    limit = max(1, min(int(limit), 50))

    conditions = [
        "LOWER(transaction_type) = 'expense'"
    ]
    params = []

    if year is not None:
        conditions.append(
            "EXTRACT(YEAR FROM transaction_date) = %s"
        )
        params.append(int(year))

    if month is not None:
        conditions.append(
            "EXTRACT(MONTH FROM transaction_date) = %s"
        )
        params.append(int(month))

    where_clause = " AND ".join(conditions)

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                f"""
                SELECT
                    transaction_date,
                    description,
                    amount,
                    COALESCE(category, 'Uncategorized'),
                    COALESCE(account, 'Unknown')
                FROM transactions
                WHERE {where_clause}
                ORDER BY amount DESC, transaction_date DESC, id DESC
                LIMIT %s
                """,
                tuple(params + [limit])
            )

            rows = cursor.fetchall()

    return [
        {
            "date": row[0],
            "description": row[1] or "No description",
            "amount": float(row[2] or 0),
            "category": row[3],
            "account": row[4],
        }
        for row in rows
    ]


def get_outstanding_customers(limit=None):
    """
    Return customers ranked by verified outstanding invoice balance.
    Payments are aggregated before joining to invoices to avoid
    multiplying invoice amounts.
    """

    query = """
        SELECT
            i.client,
            COALESCE(SUM(i.amount), 0) AS invoiced,
            COALESCE(SUM(payment_totals.total_paid), 0) AS paid,
            COALESCE(SUM(
                GREATEST(
                    COALESCE(i.amount, 0)
                    - COALESCE(payment_totals.total_paid, 0),
                    0
                )
            ), 0) AS outstanding,
            COUNT(*) FILTER (
                WHERE GREATEST(
                    COALESCE(i.amount, 0)
                    - COALESCE(payment_totals.total_paid, 0),
                    0
                ) > 0
            ) AS open_invoice_count
        FROM invoices i
        LEFT JOIN (
            SELECT
                invoice_number,
                COALESCE(SUM(amount_paid), 0) AS total_paid
            FROM payment_events
            GROUP BY invoice_number
        ) payment_totals
            ON payment_totals.invoice_number = i.invoice_number
        GROUP BY i.client
        HAVING COALESCE(SUM(
            GREATEST(
                COALESCE(i.amount, 0)
                - COALESCE(payment_totals.total_paid, 0),
                0
            )
        ), 0) > 0
        ORDER BY outstanding DESC
    """

    params = ()

    if limit is not None:
        safe_limit = max(1, min(int(limit), 100))
        query += " LIMIT %s"
        params = (safe_limit,)

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(query, params)
            rows = cursor.fetchall()

    return [
        {
            "client": row[0] or "Unknown",
            "invoiced": float(row[1] or 0),
            "paid": float(row[2] or 0),
            "outstanding": float(row[3] or 0),
            "open_invoice_count": int(row[4] or 0),
        }
        for row in rows
    ]


def get_collection_priorities(limit=5):
    """
    Return unpaid invoices ranked for collection attention.

    Ranking is deterministic:
    overdue invoices first, then earliest due date, then largest balance.
    """

    limit = max(1, min(int(limit), 50))

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    i.invoice_number,
                    i.client,
                    i.amount,
                    i.status,
                    i.due_date,
                    COALESCE(payment_totals.total_paid, 0) AS total_paid,
                    GREATEST(
                        COALESCE(i.amount, 0)
                        - COALESCE(payment_totals.total_paid, 0),
                        0
                    ) AS outstanding
                FROM invoices i
                LEFT JOIN (
                    SELECT
                        invoice_number,
                        COALESCE(SUM(amount_paid), 0) AS total_paid
                    FROM payment_events
                    GROUP BY invoice_number
                ) payment_totals
                    ON payment_totals.invoice_number = i.invoice_number
                WHERE GREATEST(
                    COALESCE(i.amount, 0)
                    - COALESCE(payment_totals.total_paid, 0),
                    0
                ) > 0
                ORDER BY
                    CASE
                        WHEN LOWER(COALESCE(i.status, '')) = 'overdue'
                        THEN 0
                        ELSE 1
                    END,
                    NULLIF(i.due_date, '')::date ASC NULLS LAST,
                    outstanding DESC
                LIMIT %s
                """,
                (limit,)
            )

            rows = cursor.fetchall()

    today = date.today()
    results = []

    for row in rows:
        due_date = row[4]
        parsed_due_date = None

        if due_date:
            if isinstance(due_date, date):
                parsed_due_date = due_date
            else:
                try:
                    parsed_due_date = date.fromisoformat(str(due_date))
                except ValueError:
                    parsed_due_date = None

        days_overdue = 0

        if parsed_due_date and parsed_due_date < today:
            days_overdue = (today - parsed_due_date).days

        results.append({
            "invoice_number": row[0],
            "client": row[1] or "Unknown",
            "invoice_amount": float(row[2] or 0),
            "status": row[3] or "Unknown",
            "due_date": parsed_due_date,
            "total_paid": float(row[5] or 0),
            "outstanding": float(row[6] or 0),
            "days_overdue": days_overdue,
        })

    return results


def get_monthly_financial_snapshot(year, month):
    """
    Return a verified monthly snapshot used for questions such as:
    'What was my net cash flow this month?'
    """

    pnl = get_monthly_profit_and_loss(
        int(year),
        int(month)
    )

    expenses = get_spending_by_category(
        year=int(year),
        month=int(month)
    )

    return {
        "year": int(year),
        "month": int(month),
        "income": float(pnl["income"]),
        "expenses": float(pnl["expenses"]),
        "net_cash_flow": float(pnl["net_profit"]),
        "expense_breakdown": expenses,
    }